export default {
  savingsOpportunity: {
    id: 1,
    title: '',
    value: '',
    secondaryValue: '',
    secondaryUnit: '',
    __typename: 'SavingsOpportunity',
  },
  selectedClient: {
    id: null,
    clientName: '',
    clientNameFull: '',
    clientTag: '',
    defaultCurrencyCode: '',
    defaultDistanceUnits: '',
    description: '',
    gcn: '',
    industry: '',
    isActive: false,
    __typename: 'ClientData',
  },
  riskArea: {
    id: 1,
    title: '',
    value: '',
    secondaryValue: '',
    secondaryUnit: '',
    __typename: 'RiskArea',
  },
}
